var noTemplate="环节未设置或未启用通知模板，请在通知模板中设置相应模板！";
var POS_REPORT_HINT="请选择需要进行报批的数据！";
var POS_REVOKE_HINT="请选择需要进行撤回的数据！";
var POS_APPROVE_HINT="请选择需要进行批准的数据！";
var POS_RETURN_HINT="请选择需要进行退回的数据！";
var POS_REPORT_WHETHER="您确定要报批所选职位吗？";
var POS_REVOKE_WHETHER="您确定要撤回所选职位吗？";
var POS_APPROVE_WHETHER="您确定要批准所选职位吗？";
var POS_RETURN_WHETHER="您确定要退回所选职位吗？";
var PROMPT_INFORMATION="提示信息";
var RETURN_OPINION="退回意见";
var Fill_RETURN_OPINION="请填写退回意见！";
var SET_EMAIL_TEMPLATE="请在通知模板中设置职位推荐模板！"
var SET_FORWARD_RESUME_TEMPLATE="请在通知模板中设置转发简历模板！"
var SET_APPRAISAL_RESUME_TEMPLATE="请在通知模板中设置简历评价模板！"
var SET_Batch_RESUME_TEMPLATE="请在通知模板中设置招聘批次模板！"
var DETERMINE_DELETE_MEMBER="确认要删除该成员吗? "
var DETERMINE_DELETE_PRINCIPAL="确认要删除部门负责人吗? "
var EXIST_POS="角色已添加！";
var set_center_template="请在通知模板中设置简历中心通知模板！"
var DATE_FORMAT_YEAR="的格式应为：yyyy(年)";
var DATE_FORMAT_MONTH="的格式应为：yyyy(年)-MM(月)";
var DATE_FORMAT_DAY="的格式应为：yyyy(年)-MM(月)-dd(日)";
var DATE_FORMAT_MINUTE="的格式应为：yyyy(年)-MM(月)-dd(日) <br /> HH(时)-ii(分)";
var DATE_FORMAT_SECOND="的格式应为：yyyy(年)-MM(月)-dd(日) <br /> HH(时)-ii(分)-ss(秒)";
var RESUME_EXPORT_PDF="正在导出简历pdf，请稍候……";
var RESUME_EXPORT_WORD="正在导出简历word，请稍候……";
var EXPORT_FAILED_MESSAGE="没有可导出的应聘人员数据";
var CREATE_NEW_POSITION="创建新轮招聘职位";
var STARDATE_NOTBEFORE_ENDDATE="有效起始日期不能大于有效结束日期";
var ORGANIZATION_CANNOT_EMPTY="请选择所属机构！";
var INDEX_SAVE_FINISH="简历指标保存完毕";
var SUBSET_SAVE_FINISH="简历子集保存完毕";
var STATE_CANNOT_STOP="当前状态无法暂停，仅已发布状态的职位可以暂停！";
var IS_STOP_STATE="已经是暂停状态！";
var STATE_CANNOT_PUBLISH="当前状态无法发布，仅已批和暂停状态的职位可以发布！";
var IS_PUBLISH_STATE="已经是发布状态！";
var STATE_CANNOT_END="当前状态无法结束，仅已发布状态的职位可以结束！";
var IS_END_STATE="已经是结束状态！";
var CANNOT_DELETE_POSITION="不能删除处于已发布，已批，待批状态的职位！";
var STATE_CANNOT_REPORT="当前状态无法报批，仅起草和退回状态的职位可以报批！";
var STATE_CANNOT_REVOKE="当前状态无法撤回，仅待批状态的职位可以撤回！";
var STATE_CANNOT_APPROVE="当前状态无法批准，仅待批和退回状态的职位可以批准！";
var STATE_CANNOT_RETURN="当前状态无法退回，仅待批和已批状态的职位可以退回！";
var SET_TEMPLATE="请先设置通知模板！ ";
var ALL_INPUT_FINISH="请将全部的输入项填写完以后再提交！  ";
var END_STATE_CREATION="非结束状态职位不允许发起新轮招聘！";
var PEOPLE_NUMBER_LIMIT="招聘人数必须为3位以内整数！";
var RECRUITS_NUMBER_MINNIMUM="招聘人数最小为1!";
var NEW_POSITION_INITIATE="新轮招聘职位已发起，请到进行中状态查看起草状态职位，并可自行重新设置到岗日期！";
var UNKNOW_POSITION_CANNOT="未知职位不能发起新轮招聘！";
var ENDTIME_NOTLESS_NOWTIME="新轮招聘职位结束时间不能小于当前系统时间！";
var ENTER_DATE_FORMAT_ERROR="输入的日期数据格式不对，请修改！";
var PROCESS_NAME_NOT_STANDARD="流程名称不能为空 ！";
var NOTIFICATION_CONTENT_ISNOTEMPT="通知内容不能为空 ！";
var EXAM_STARDATE_NOTBEFORE_ENDDATE="考试起始时间不能晚于考试结束时间！";
var AUDITION_DATE__FORMAT="面试日期的格式应为：yyyy(年)-MM(月)-dd(日) HH(时)-ii(分)"
var BATCHNAME_MORE_LONG="批次名称不能超过25个汉字或者50个字母数字，请修改 ！"
var LINK_NAME_NOT_STANDARD="环节名称不能为空 ！";
var REGISTRATION_DEADLINE_INCORRECT="注册截止时间格式不正确，请重新输入 ！"; 
var PARAMETER_SETTING_ENTRY_PERSONNELLIBRARY="请到“招聘设置/参数设置/后台参数/基础参数”指定入 职人员库！";
var DONOT_ACCEPT_JOB_APPLICATIONS="当前人员处于已终止或已入职状态，不允许接受职位申请！";
var CANNOT_DELETE_BATCH="不能删除处于已发布状态的批次！";
var CHOOSE_A_BATCH_SEND_NOTIFICATION="只能选择一个批次发送通知！ ";
var IMPORT_RESUME_MSG="提示信息";
var FILTER_CANNOT_BE_EMPTY="筛选器名称不能为空";
var APPLICANT_STATUS_MUST_SET="“应聘身份”必须设置，请进行设置！";
var ENDTIME_NOTLESS_STARTTIME="报名起始日期不能大于报名截止日期！";
var STATE_CANNOT_PUBLISHWITHAPPROVE="当前状态无法发布，仅待批，已批和暂停状态的职位可以发布！";
var NO_JOBMODULE_PURVIEW="您没有招聘模块的管理范围权限！请联系管理员";
var NOTIFICATION_SENT_SUCCESSFULLY="通知发送成功！";
var ONLY_CHOOSE_POSTSTATUS_POSITION="只有处于发布状态的职位可以进行人岗匹配！";




